version: "3.8"
services:
  django-sr:
    container_name: django-sr
    build: ./django
    command: bash -c "python3 manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./django/.env
    depends_on:
      - postgres
    networks:
      - default

  postgres-sr:
    container_name: postgres-sr
    build: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d
    env_file: ./postgres/.env_db
    ports:
      - 5434:5432

  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - django-sr
      - nuxtjs-sr

  nuxtjs-sr:
    build: ./nuxtjs
    container_name: nuxtjs-sr
    command: sh -c "yarn install && yarn build && yarn start"
    ports:
      - "3001:3000"
    working_dir: "/src"
    volumes:
      - "./nuxtjs:/src"
      - node_modules_volume:/src/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default

volumes:
  node_modules_volume:



      

      
